import { REST, Routes } from 'discord.js';
import config from '../schemas/config'; 
import { fetchMinecraftVersions } from '../utils/minecraftApi';

export async function registerCommands() {
  const rest = new REST({ version: '10' }).setToken(config.DISCORD_TOKEN);

  const minecraftVersions = await fetchMinecraftVersions();

  try {
    console.log('Started refreshing application (/) commands.');

    const commands = [
      {
        name: 'create',
        description: 'Create a Minecraft server',
        options: [
          {
            name: 'name',
            description: 'The name of the server',
            type: 3, // STRING
            required: true
          },
          {
            name: 'version',
            description: 'Minecraft version',
            type: 3, // STRING
            required: true,
            choices: minecraftVersions,
          },
          {
            name: 'maxplayers',
            description: 'Maximum number of players',
            type: 4, // INTEGER
            required: true
          },
          {
            name: 'gamemode',
            description: 'Game mode (default: survival)',
            type: 3, // STRING
            required: false,
            choices: [
              { name: 'Survival', value: 'survival' },
              { name: 'Creative', value: 'creative' },
              { name: 'Adventure', value: 'adventure' },
              { name: 'Spectator', value: 'spectator' },
            ],
          },
          {
            name: 'difficulty',
            description: 'Difficulty level (default: normal)',
            type: 3, // STRING
            required: false,
            choices: [
              { name: 'Peaceful', value: 'peaceful' },
              { name: 'Easy', value: 'easy' },
              { name: 'Normal', value: 'normal' },
              { name: 'Hard', value: 'hard' },
            ],
          },
          {
            name: 'hardcore',
            description: 'Enable hardcore mode (default: false)',
            type: 5, // BOOLEAN
            required: false
          },
          {
            name: 'allowpvp',
            description: 'Allow PvP (default: true)',
            type: 5, // BOOLEAN
            required: false
          },
          {
            name: 'allownether',
            description: 'Allow Nether dimension (default: true)',
            type: 5, // BOOLEAN
            required: false
          },
          {
            name: 'onlinemode',
            description: 'Online mode (default: true)',
            type: 5, // BOOLEAN
            required: false
          },
          {
            name: 'motd',
            description: 'Message of the day (default: "Server generated by Discord Bot")',
            type: 3, // STRING
            required: false
          },
        ],
      },
      {
        name: 'status',
        description: 'Check the status of the Minecraft server',
      },
    ];

    if (process.env.NODE_ENV === 'development') {
      await rest.put(
        Routes.applicationGuildCommands(config.DISCORD_CLIENT_ID, config.GUILD_ID),
        { body: commands }
      );
      console.log('Successfully reloaded guild-specific commands.');
    } else {
      await rest.put(
        Routes.applicationCommands(config.DISCORD_CLIENT_ID),
        { body: commands }
      );
      console.log('Successfully reloaded global commands.');
    }
  } catch (error) {
    console.error('Error registering commands:', error);
  }
}
